services:
  # Next.js Web Service
  - type: web
    name: bolinaohonda-web
    runtime: node
    plan: free
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CLIENT_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
    healthCheckPath: /

  # Express API Service
  - type: web
    name: bolinaohonda-api
    runtime: node
    plan: free
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
    healthCheckPath: /health

databases:
  # MySQL Database
  - name: bolinaohonda-db
    plan: free
    databaseName: bolinaohonda
    user: bolinaohonda
